/**
 * National Enterprise & Nodal Officer Directory (Comprehensive Index)
 * Stores pre-configured official grievance nodal emails, ombudsman categories, and resolution SLAs.
 */

const COMPANY_DIRECTORY = [
  // ==========================================
  // 1. E-COMMERCE, RETAIL & QUICK COMMERCE
  // ==========================================
  {
    id: "amazon",
    name: "Amazon India",
    category: "Product",
    nodalEmail: "grievance-officer@amazon.in",
    supportEmail: "cs-reply@amazon.in",
    ombudsman: "National Consumer Disputes Redressal Commission (NCDRC / e-Daakhil)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "flipkart",
    name: "Flipkart",
    category: "Product",
    nodalEmail: "grievance.officer@flipkart.com",
    supportEmail: "support@flipkart.com",
    ombudsman: "National Consumer Disputes Redressal Commission (NCDRC / e-Daakhil)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "myntra",
    name: "Myntra",
    category: "Product",
    nodalEmail: "grievanceofficer@myntra.com",
    supportEmail: "support@myntra.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "meesho",
    name: "Meesho",
    category: "Product",
    nodalEmail: "grievance-officer@meesho.com",
    supportEmail: "help@meesho.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "ajio",
    name: "Ajio (Reliance Retail)",
    category: "Product",
    nodalEmail: "grievance.officer@ajio.com",
    supportEmail: "customercare@ajio.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "nykaa",
    name: "Nykaa",
    category: "Product",
    nodalEmail: "grievanceofficer@nykaa.com",
    supportEmail: "support@nykaa.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "tatacliq",
    name: "Tata CLiQ",
    category: "Product",
    nodalEmail: "grievanceofficer@tatacliq.com",
    supportEmail: "support@tatacliq.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "jiomart",
    name: "JioMart (Reliance)",
    category: "Product",
    nodalEmail: "grievanceofficer@jiomart.com",
    supportEmail: "cs@jiomart.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "croma",
    name: "Croma Electronics (Infiniti Retail)",
    category: "Product",
    nodalEmail: "grievanceofficer@croma.com",
    supportEmail: "customersupport@croma.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "reliancedigital",
    name: "Reliance Digital",
    category: "Product",
    nodalEmail: "reliancedigital@ril.com",
    supportEmail: "reliancedigital@ril.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "vijaysales",
    name: "Vijay Sales",
    category: "Product",
    nodalEmail: "support@vijaysales.com",
    supportEmail: "customercare@vijaysales.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "lenskart",
    name: "Lenskart",
    category: "Product",
    nodalEmail: "grievance@lenskart.in",
    supportEmail: "support@lenskart.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 5,
  },
  {
    id: "firstcry",
    name: "FirstCry",
    category: "Product",
    nodalEmail: "grievanceofficer@firstcry.com",
    supportEmail: "customercare@firstcry.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "snapdeal",
    name: "Snapdeal",
    category: "Product",
    nodalEmail: "grievanceofficer@snapdeal.com",
    supportEmail: "help@snapdeal.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },

  // ==========================================
  // 2. FOOD, DINING & QUICK COMMERCE
  // ==========================================
  {
    id: "zomato",
    name: "Zomato",
    category: "Food",
    nodalEmail: "grievance@zomato.com",
    supportEmail: "support@zomato.com",
    ombudsman: "FSSAI & National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },
  {
    id: "swiggy",
    name: "Swiggy",
    category: "Food",
    nodalEmail: "grievances@swiggy.in",
    supportEmail: "support@swiggy.in",
    ombudsman: "FSSAI & National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },
  {
    id: "blinkit",
    name: "Blinkit",
    category: "Food",
    nodalEmail: "grievance@blinkit.com",
    supportEmail: "info@blinkit.com",
    ombudsman: "FSSAI & National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },
  {
    id: "zepto",
    name: "Zepto",
    category: "Food",
    nodalEmail: "grievance@zeptonow.com",
    supportEmail: "support@zeptonow.com",
    ombudsman: "FSSAI & National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },
  {
    id: "bigbasket",
    name: "BigBasket",
    category: "Food",
    nodalEmail: "grievance@bigbasket.com",
    supportEmail: "customerservice@bigbasket.com",
    ombudsman: "FSSAI & National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },
  {
    id: "dominos",
    name: "Domino's Pizza India",
    category: "Food",
    nodalEmail: "guestcare@jublfood.com",
    supportEmail: "guestcare@jublfood.com",
    ombudsman: "FSSAI & National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },
  {
    id: "mcdonalds",
    name: "McDonald's India (Westlife / CPRL)",
    category: "Food",
    nodalEmail: "customerfeedback@mcdonaldsindia.com",
    supportEmail: "care@mcdonaldsindia.com",
    ombudsman: "FSSAI & National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },
  {
    id: "kfc",
    name: "KFC India (Yum! Brands)",
    category: "Food",
    nodalEmail: "feedback@kfc.com",
    supportEmail: "contact@kfc.com",
    ombudsman: "FSSAI & National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },
  {
    id: "pizzahut",
    name: "Pizza Hut India",
    category: "Food",
    nodalEmail: "feedback@pizzahut.co.in",
    supportEmail: "support@pizzahut.co.in",
    ombudsman: "FSSAI & National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },
  {
    id: "burgerking",
    name: "Burger King India",
    category: "Food",
    nodalEmail: "customercare@burgerking.in",
    supportEmail: "contact@burgerking.in",
    ombudsman: "FSSAI & National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },
  {
    id: "starbucks",
    name: "Tata Starbucks India",
    category: "Food",
    nodalEmail: "customercare@tatastarbucks.com",
    supportEmail: "care@tatastarbucks.com",
    ombudsman: "FSSAI & National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },

  // ==========================================
  // 3. BANKING, CARDS, UPI & FINTECH
  // ==========================================
  {
    id: "sbi",
    name: "State Bank of India (SBI)",
    category: "Banking",
    nodalEmail: "nodalofficer@sbi.co.in",
    supportEmail: "customercare@sbi.co.in",
    ombudsman: "RBI Integrated Ombudsman Scheme (cms.rbi.org.in)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "hdfc",
    name: "HDFC Bank",
    category: "Banking",
    nodalEmail: "grievance.redressal@hdfcbank.com",
    supportEmail: "support@hdfcbank.com",
    ombudsman: "RBI Integrated Ombudsman Scheme (cms.rbi.org.in)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "icici",
    name: "ICICI Bank",
    category: "Banking",
    nodalEmail: "headservicequality@icicibank.com",
    supportEmail: "customer.care@icicibank.com",
    ombudsman: "RBI Integrated Ombudsman Scheme (cms.rbi.org.in)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "axis",
    name: "Axis Bank",
    category: "Banking",
    nodalEmail: "nodal.officer@axisbank.com",
    supportEmail: "customer.services@axisbank.com",
    ombudsman: "RBI Integrated Ombudsman Scheme (cms.rbi.org.in)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "kotak",
    name: "Kotak Mahindra Bank",
    category: "Banking",
    nodalEmail: "nodalofficer@kotak.com",
    supportEmail: "service.bank@kotak.com",
    ombudsman: "RBI Integrated Ombudsman Scheme (cms.rbi.org.in)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "pnb",
    name: "Punjab National Bank (PNB)",
    category: "Banking",
    nodalEmail: "care@pnb.co.in",
    supportEmail: "care@pnb.co.in",
    ombudsman: "RBI Integrated Ombudsman Scheme (cms.rbi.org.in)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "bankofbaroda",
    name: "Bank of Baroda",
    category: "Banking",
    nodalEmail: "gm.ops.ho@bankofbaroda.com",
    supportEmail: "customercare@bankofbaroda.com",
    ombudsman: "RBI Integrated Ombudsman Scheme (cms.rbi.org.in)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "canarabank",
    name: "Canara Bank",
    category: "Banking",
    nodalEmail: "cpc@canarabank.com",
    supportEmail: "hocanarabank@canarabank.com",
    ombudsman: "RBI Integrated Ombudsman Scheme (cms.rbi.org.in)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "indusind",
    name: "IndusInd Bank",
    category: "Banking",
    nodalEmail: "nodal.officer@indusind.com",
    supportEmail: "reachus@indusind.com",
    ombudsman: "RBI Integrated Ombudsman Scheme (cms.rbi.org.in)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "idfcfirst",
    name: "IDFC FIRST Bank",
    category: "Banking",
    nodalEmail: "nodalofficer@idfcfirstbank.com",
    supportEmail: "banker@idfcfirstbank.com",
    ombudsman: "RBI Integrated Ombudsman Scheme (cms.rbi.org.in)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "yesbank",
    name: "Yes Bank",
    category: "Banking",
    nodalEmail: "principal.nodalofficer@yesbank.in",
    supportEmail: "yestouch@yesbank.in",
    ombudsman: "RBI Integrated Ombudsman Scheme (cms.rbi.org.in)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "phonepe",
    name: "PhonePe (UPI & Payments)",
    category: "Banking",
    nodalEmail: "grievance-officer@phonepe.com",
    supportEmail: "support@phonepe.com",
    ombudsman: "NPCI & RBI Ombudsman",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "paytm",
    name: "Paytm Payments",
    category: "Banking",
    nodalEmail: "grievanceofficer@paytm.com",
    supportEmail: "care@paytm.com",
    ombudsman: "NPCI & RBI Ombudsman",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "googlepay",
    name: "Google Pay India",
    category: "Banking",
    nodalEmail: "gpay-grievance-india@google.com",
    supportEmail: "support-in@google.com",
    ombudsman: "NPCI & RBI Ombudsman",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "cred",
    name: "CRED",
    category: "Banking",
    nodalEmail: "grievance@cred.club",
    supportEmail: "feedback@cred.club",
    ombudsman: "RBI Integrated Ombudsman Scheme",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "bharatpe",
    name: "BharatPe",
    category: "Banking",
    nodalEmail: "nodal@bharatpe.com",
    supportEmail: "support@bharatpe.com",
    ombudsman: "RBI Ombudsman",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "zerodha",
    name: "Zerodha Broking",
    category: "Banking",
    nodalEmail: "complaints@zerodha.com",
    supportEmail: "support@zerodha.com",
    ombudsman: "SEBI SCORES (scores.sebi.gov.in)",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "groww",
    name: "Groww (Nextbillion Technology)",
    category: "Banking",
    nodalEmail: "grievance@groww.in",
    supportEmail: "support@groww.in",
    ombudsman: "SEBI SCORES & RBI Ombudsman",
    slaHours: 24,
    slaDays: 5,
  },

  // ==========================================
  // 4. TELECOM & BROADBAND ISPS
  // ==========================================
  {
    id: "jio",
    name: "Reliance Jio Infocomm",
    category: "Telecom",
    nodalEmail: "appellate.authority@jio.com",
    supportEmail: "care@jio.com",
    ombudsman: "TRAI Telecom Dispute Settlement Appellate Tribunal (TDSAT)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "airtel",
    name: "Bharti Airtel",
    category: "Telecom",
    nodalEmail: "nodalofficer.india@airtel.com",
    supportEmail: "121@in.airtel.com",
    ombudsman: "TRAI Telecom Dispute Settlement Appellate Tribunal (TDSAT)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "vi",
    name: "Vodafone Idea (Vi)",
    category: "Telecom",
    nodalEmail: "nodalofficer@vodafoneidea.com",
    supportEmail: "customercare@vodafoneidea.com",
    ombudsman: "TRAI Telecom Dispute Settlement Appellate Tribunal (TDSAT)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "bsnl",
    name: "BSNL India",
    category: "Telecom",
    nodalEmail: "cmdbsnl@bsnl.co.in",
    supportEmail: "portalhelpdesk@bsnl.co.in",
    ombudsman: "TRAI & DOT Grievance Portal",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "actfibernet",
    name: "ACT Fibernet (Atria Convergence)",
    category: "Telecom",
    nodalEmail: "nodal@actcorp.in",
    supportEmail: "support@actcorp.in",
    ombudsman: "TRAI & DOT Grievance Portal",
    slaHours: 48,
    slaDays: 5,
  },
  {
    id: "tataplayfiber",
    name: "Tata Play Fiber",
    category: "Telecom",
    nodalEmail: "nodalofficer@tataplayfiber.co.in",
    supportEmail: "care@tataplayfiber.co.in",
    ombudsman: "TRAI & TDSAT",
    slaHours: 48,
    slaDays: 5,
  },

  // ==========================================
  // 5. TRAVEL, AIRLINES, RAILWAYS & MOBILITY
  // ==========================================
  {
    id: "makemytrip",
    name: "MakeMyTrip",
    category: "Travel",
    nodalEmail: "grievance.officer@makemytrip.com",
    supportEmail: "service@makemytrip.com",
    ombudsman: "Ministry of Civil Aviation / AirSewa & NCDRC",
    slaHours: 24,
    slaDays: 7,
  },
  {
    id: "irctc",
    name: "IRCTC (Indian Railways)",
    category: "Travel",
    nodalEmail: "customercare@irctc.co.in",
    supportEmail: "care@irctc.co.in",
    ombudsman: "RailMadad Grievance Redressal Mechanism",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "indigo",
    name: "IndiGo Airlines",
    category: "Travel",
    nodalEmail: "nodalofficer@goindigo.in",
    supportEmail: "customer.relations@goindigo.in",
    ombudsman: "AirSewa / DGCA Passenger Redressal",
    slaHours: 24,
    slaDays: 7,
  },
  {
    id: "airindia",
    name: "Air India",
    category: "Travel",
    nodalEmail: "nodalofficer@airindia.com",
    supportEmail: "contactus@airindia.com",
    ombudsman: "AirSewa / DGCA Passenger Redressal",
    slaHours: 24,
    slaDays: 7,
  },
  {
    id: "spicejet",
    name: "SpiceJet Airlines",
    category: "Travel",
    nodalEmail: "nodalofficer@spicejet.com",
    supportEmail: "custrelations@spicejet.com",
    ombudsman: "AirSewa / DGCA Passenger Redressal",
    slaHours: 24,
    slaDays: 7,
  },
  {
    id: "akasaair",
    name: "Akasa Air",
    category: "Travel",
    nodalEmail: "nodalofficer@akasaair.com",
    supportEmail: "support@akasaair.com",
    ombudsman: "AirSewa / DGCA Passenger Redressal",
    slaHours: 24,
    slaDays: 7,
  },
  {
    id: "uber",
    name: "Uber India",
    category: "Travel",
    nodalEmail: "grievance-officer-india@uber.com",
    supportEmail: "support@uber.com",
    ombudsman: "Central Consumer Protection Authority (CCPA)",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "ola",
    name: "Ola Cabs",
    category: "Travel",
    nodalEmail: "grievanceofficer@olacabs.com",
    supportEmail: "support@olacabs.com",
    ombudsman: "Central Consumer Protection Authority (CCPA)",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "rapido",
    name: "Rapido Bike Taxi",
    category: "Travel",
    nodalEmail: "grievance@rapido.bike",
    supportEmail: "shoutout@rapido.bike",
    ombudsman: "Central Consumer Protection Authority (CCPA)",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "easemytrip",
    name: "EaseMyTrip",
    category: "Travel",
    nodalEmail: "care@easemytrip.com",
    supportEmail: "care@easemytrip.com",
    ombudsman: "Ministry of Civil Aviation / AirSewa",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "cleartrip",
    name: "Cleartrip",
    category: "Travel",
    nodalEmail: "grievance@cleartrip.com",
    supportEmail: "support@cleartrip.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "yatra",
    name: "Yatra Online",
    category: "Travel",
    nodalEmail: "grievance@yatra.com",
    supportEmail: "support@yatra.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "redbus",
    name: "RedBus (MakeMyTrip Group)",
    category: "Travel",
    nodalEmail: "grievances@redbus.in",
    supportEmail: "support@redbus.in",
    ombudsman: "National Consumer Helpline",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "oyo",
    name: "OYO Rooms",
    category: "Travel",
    nodalEmail: "grievanceofficer@oyorooms.com",
    supportEmail: "partner@oyorooms.com",
    ombudsman: "National Consumer Disputes Redressal Commission",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "airbnb",
    name: "Airbnb India",
    category: "Travel",
    nodalEmail: "grievance-india@airbnb.com",
    supportEmail: "support-india@airbnb.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 24,
    slaDays: 5,
  },

  // ==========================================
  // 6. ELECTRONICS, SMARTPHONES & COMPUTERS
  // ==========================================
  {
    id: "samsung",
    name: "Samsung Electronics India",
    category: "Product",
    nodalEmail: "grievance.india@samsung.com",
    supportEmail: "support.india@samsung.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "apple",
    name: "Apple India",
    category: "Product",
    nodalEmail: "india_grievance_officer@apple.com",
    supportEmail: "contactus.in@apple.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "xiaomi",
    name: "Xiaomi / Redmi India",
    category: "Product",
    nodalEmail: "grievance-officer@xiaomi.com",
    supportEmail: "service.in@xiaomi.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "oneplus",
    name: "OnePlus India",
    category: "Product",
    nodalEmail: "grievance.officer@oneplus.com",
    supportEmail: "onepluscare@oneplus.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "realme",
    name: "Realme India",
    category: "Product",
    nodalEmail: "grievance@realme.com",
    supportEmail: "service.in@realme.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "vivo",
    name: "Vivo India",
    category: "Product",
    nodalEmail: "grievance@vivo.com",
    supportEmail: "care@vivo.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "oppo",
    name: "Oppo India",
    category: "Product",
    nodalEmail: "grievance@oppo.com",
    supportEmail: "support.in@oppo.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "sony",
    name: "Sony India",
    category: "Product",
    nodalEmail: "sonyindia.care@sony.com",
    supportEmail: "sonyindia.care@sony.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "hp",
    name: "HP India (Hewlett Packard)",
    category: "Product",
    nodalEmail: "in.contact@hp.com",
    supportEmail: "in.contact@hp.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "dell",
    name: "Dell Technologies India",
    category: "Product",
    nodalEmail: "india_customer_care@dell.com",
    supportEmail: "india_customer_care@dell.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "lenovo",
    name: "Lenovo India",
    category: "Product",
    nodalEmail: "grievance@lenovo.com",
    supportEmail: "customercare@lenovo.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "asus",
    name: "Asus India",
    category: "Product",
    nodalEmail: "support_india@asus.com",
    supportEmail: "support_india@asus.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "boat",
    name: "boAt Lifestyle (Imagine Marketing)",
    category: "Product",
    nodalEmail: "nodalofficer@imaginemarketingindia.com",
    supportEmail: "info@imaginemarketingindia.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 5,
  },
  {
    id: "noise",
    name: "Noise (Nexxbase Marketing)",
    category: "Product",
    nodalEmail: "grievance@gonoise.com",
    supportEmail: "help@gonoise.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 5,
  },

  // ==========================================
  // 7. HOME APPLIANCES & CONSUMER DURABLES
  // ==========================================
  {
    id: "lg",
    name: "LG Electronics India",
    category: "Product",
    nodalEmail: "serviceindia@lge.com",
    supportEmail: "serviceindia@lge.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "whirlpool",
    name: "Whirlpool of India",
    category: "Product",
    nodalEmail: "grievanceofficer@whirlpool.com",
    supportEmail: "helpdeskindia@whirlpool.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "voltas",
    name: "Voltas (Tata Enterprise)",
    category: "Product",
    nodalEmail: "nodalofficer@voltas.com",
    supportEmail: "customercare@voltas.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "havells",
    name: "Havells India (Lloyd)",
    category: "Product",
    nodalEmail: "grievance@havells.com",
    supportEmail: "customercare@havells.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "godrej",
    name: "Godrej & Boyce (Appliances)",
    category: "Product",
    nodalEmail: "smartcare@godrej.com",
    supportEmail: "smartcare@godrej.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "bosch",
    name: "Bosch Home Appliances India",
    category: "Product",
    nodalEmail: "service.in@bosch.com",
    supportEmail: "service.in@bosch.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "eurekaforbes",
    name: "Eureka Forbes (Aquaguard)",
    category: "Product",
    nodalEmail: "customercare@eurekaforbes.com",
    supportEmail: "customercare@eurekaforbes.com",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 5,
  },
  {
    id: "kent",
    name: "Kent RO Systems",
    category: "Product",
    nodalEmail: "service@kent.co.in",
    supportEmail: "service@kent.co.in",
    ombudsman: "National Consumer Helpline (1915)",
    slaHours: 48,
    slaDays: 5,
  },

  // ==========================================
  // 8. AUTOMOBILE, TWO-WHEELERS & EV
  // ==========================================
  {
    id: "tatamotors",
    name: "Tata Motors Passenger Vehicles",
    category: "Product",
    nodalEmail: "nodalofficer@tatamotors.com",
    supportEmail: "customercare@tatamotors.com",
    ombudsman: "National Consumer Disputes Redressal Commission (NCDRC)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "marutisuzuki",
    name: "Maruti Suzuki India",
    category: "Product",
    nodalEmail: "nodal@maruti.co.in",
    supportEmail: "contact@maruti.co.in",
    ombudsman: "National Consumer Disputes Redressal Commission (NCDRC)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "hyundai",
    name: "Hyundai Motor India",
    category: "Product",
    nodalEmail: "nodalofficer@hmil.net",
    supportEmail: "cr@hmil.net",
    ombudsman: "National Consumer Disputes Redressal Commission (NCDRC)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "mahindra",
    name: "Mahindra & Mahindra (Automotive)",
    category: "Product",
    nodalEmail: "customercare@mahindra.com",
    supportEmail: "customercare@mahindra.com",
    ombudsman: "National Consumer Disputes Redressal Commission (NCDRC)",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "olaelectric",
    name: "Ola Electric Mobility",
    category: "Product",
    nodalEmail: "nodal@olaelectric.com",
    supportEmail: "support@olaelectric.com",
    ombudsman: "Central Consumer Protection Authority (CCPA)",
    slaHours: 24,
    slaDays: 7,
  },
  {
    id: "ather",
    name: "Ather Energy",
    category: "Product",
    nodalEmail: "grievance@atherenergy.com",
    supportEmail: "customercare@atherenergy.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "tvsmotor",
    name: "TVS Motor Company",
    category: "Product",
    nodalEmail: "customercare@tvsmotor.com",
    supportEmail: "customercare@tvsmotor.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "heromotocorp",
    name: "Hero MotoCorp",
    category: "Product",
    nodalEmail: "customercare@heromotocorp.com",
    supportEmail: "customercare@heromotocorp.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "royalenfield",
    name: "Royal Enfield (Eicher Motors)",
    category: "Product",
    nodalEmail: "support@royalenfield.com",
    supportEmail: "support@royalenfield.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 48,
    slaDays: 7,
  },

  // ==========================================
  // 9. INSURANCE, HEALTH & PHARMACY
  // ==========================================
  {
    id: "lic",
    name: "Life Insurance Corporation of India (LIC)",
    category: "Banking",
    nodalEmail: "co_crmgrv@licindia.com",
    supportEmail: "co_crmgrv@licindia.com",
    ombudsman: "IRDAI Bima Bharosa Portal (bimabharosa.irdai.gov.in)",
    slaHours: 48,
    slaDays: 14,
  },
  {
    id: "starhealth",
    name: "Star Health & Allied Insurance",
    category: "Banking",
    nodalEmail: "gro@starhealth.in",
    supportEmail: "support@starhealth.in",
    ombudsman: "IRDAI Insurance Ombudsman",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "hdfcergo",
    name: "HDFC ERGO General Insurance",
    category: "Banking",
    nodalEmail: "grievance@hdfcergo.com",
    supportEmail: "care@hdfcergo.com",
    ombudsman: "IRDAI Insurance Ombudsman",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "icicilombard",
    name: "ICICI Lombard General Insurance",
    category: "Banking",
    nodalEmail: "grievanceredressal@icicilombard.com",
    supportEmail: "customersupport@icicilombard.com",
    ombudsman: "IRDAI Insurance Ombudsman",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "carehealth",
    name: "Care Health Insurance",
    category: "Banking",
    nodalEmail: "customerfirst@careinsurance.com",
    supportEmail: "customerfirst@careinsurance.com",
    ombudsman: "IRDAI Insurance Ombudsman",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "policybazaar",
    name: "PolicyBazaar",
    category: "Banking",
    nodalEmail: "grievance@policybazaar.com",
    supportEmail: "care@policybazaar.com",
    ombudsman: "IRDAI & National Consumer Helpline",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "tata1mg",
    name: "Tata 1mg",
    category: "Product",
    nodalEmail: "grievance@1mg.com",
    supportEmail: "care@1mg.com",
    ombudsman: "CDSCO & National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },
  {
    id: "apollo247",
    name: "Apollo 24|7 (Apollo Hospitals)",
    category: "Product",
    nodalEmail: "helpdesk@apollo247.com",
    supportEmail: "helpdesk@apollo247.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },
  {
    id: "pharmeasy",
    name: "PharmEasy",
    category: "Product",
    nodalEmail: "care@pharmeasy.in",
    supportEmail: "care@pharmeasy.in",
    ombudsman: "CDSCO & National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },

  // ==========================================
  // 10. OTT, STREAMING & ENTERTAINMENT
  // ==========================================
  {
    id: "netflix",
    name: "Netflix India",
    category: "Service",
    nodalEmail: "grievance-officer-india@netflix.com",
    supportEmail: "support-in@netflix.com",
    ombudsman: "Digital Media Ethics Code / I&B Ministry",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "hotstar",
    name: "Disney+ Hotstar / JioHotstar",
    category: "Service",
    nodalEmail: "grievanceofficer@hotstar.com",
    supportEmail: "disneyplus.in@hotstar.com",
    ombudsman: "Digital Media Ethics Code / I&B Ministry",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "primevideo",
    name: "Amazon Prime Video India",
    category: "Service",
    nodalEmail: "grievanceofficer-primevideo@amazon.com",
    supportEmail: "cs-reply@amazon.in",
    ombudsman: "Digital Media Ethics Code / I&B Ministry",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "bookmyshow",
    name: "BookMyShow (Bigtree Entertainment)",
    category: "Service",
    nodalEmail: "grievance@bookmyshow.com",
    supportEmail: "helpdesk@bookmyshow.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 24,
    slaDays: 3,
  },
  {
    id: "zee5",
    name: "Zee5",
    category: "Service",
    nodalEmail: "grievanceofficer@zee.com",
    supportEmail: "support.in@zee5.com",
    ombudsman: "Digital Media Ethics Code / I&B Ministry",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "spotify",
    name: "Spotify India",
    category: "Service",
    nodalEmail: "grievance-india@spotify.com",
    supportEmail: "support@spotify.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 24,
    slaDays: 5,
  },

  // ==========================================
  // 11. LOGISTICS, COURIERS & POSTAL
  // ==========================================
  {
    id: "delhivery",
    name: "Delhivery Logistics",
    category: "Service",
    nodalEmail: "nodalofficer@delhivery.com",
    supportEmail: "customer.support@delhivery.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "bluedart",
    name: "Blue Dart Express (DHL)",
    category: "Service",
    nodalEmail: "nodal@bluedart.com",
    supportEmail: "customerservice@bluedart.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "dtdc",
    name: "DTDC Express",
    category: "Service",
    nodalEmail: "grievance@dtdc.com",
    supportEmail: "customersupport@dtdc.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "indiapost",
    name: "India Post (Speed Post)",
    category: "Service",
    nodalEmail: "complaints@indiapost.gov.in",
    supportEmail: "speedpost@indiapost.gov.in",
    ombudsman: "CPGRAMS / Department of Posts",
    slaHours: 48,
    slaDays: 7,
  },
  {
    id: "shadowfax",
    name: "Shadowfax Technologies",
    category: "Service",
    nodalEmail: "grievance@shadowfax.in",
    supportEmail: "help@shadowfax.in",
    ombudsman: "National Consumer Helpline",
    slaHours: 24,
    slaDays: 5,
  },

  // ==========================================
  // 12. ED-TECH & ONLINE LEARNING
  // ==========================================
  {
    id: "byjus",
    name: "BYJU'S (Think & Learn)",
    category: "Service",
    nodalEmail: "grievance@byjus.com",
    supportEmail: "support@byjus.com",
    ombudsman: "National Consumer Disputes Redressal Commission (NCDRC)",
    slaHours: 24,
    slaDays: 7,
  },
  {
    id: "unacademy",
    name: "Unacademy (Sorting Hat Technologies)",
    category: "Service",
    nodalEmail: "grievance@unacademy.com",
    supportEmail: "help@unacademy.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 24,
    slaDays: 7,
  },
  {
    id: "physicswallah",
    name: "Physics Wallah (PW)",
    category: "Service",
    nodalEmail: "grievance@pw.live",
    supportEmail: "support@pw.live",
    ombudsman: "National Consumer Helpline",
    slaHours: 24,
    slaDays: 5,
  },
  {
    id: "upgrad",
    name: "upGrad Education",
    category: "Service",
    nodalEmail: "grievance@upgrad.com",
    supportEmail: "customercare@upgrad.com",
    ombudsman: "National Consumer Helpline",
    slaHours: 24,
    slaDays: 7,
  },

  // ==========================================
  // 13. REAL ESTATE & HOUSING DEVELOPERS
  // ==========================================
  {
    id: "dlf",
    name: "DLF Limited",
    category: "Service",
    nodalEmail: "nodalofficer@dlf.in",
    supportEmail: "customercare@dlf.in",
    ombudsman: "Real Estate Regulatory Authority (RERA) / NCDRC",
    slaHours: 48,
    slaDays: 14,
  },
  {
    id: "godrejproperties",
    name: "Godrej Properties",
    category: "Service",
    nodalEmail: "customercare@godrejproperties.com",
    supportEmail: "customercare@godrejproperties.com",
    ombudsman: "Real Estate Regulatory Authority (RERA) / NCDRC",
    slaHours: 48,
    slaDays: 14,
  },
  {
    id: "lodha",
    name: "Macrotech Developers (Lodha)",
    category: "Service",
    nodalEmail: "customercare@lodhagroup.com",
    supportEmail: "customercare@lodhagroup.com",
    ombudsman: "Real Estate Regulatory Authority (RERA) / NCDRC",
    slaHours: 48,
    slaDays: 14,
  },
  {
    id: "prestige",
    name: "Prestige Estates Projects",
    category: "Service",
    nodalEmail: "properties@prestigeconstructions.com",
    supportEmail: "properties@prestigeconstructions.com",
    ombudsman: "Real Estate Regulatory Authority (RERA) / NCDRC",
    slaHours: 48,
    slaDays: 14,
  },
];

const findCompany = (nameOrId) => {
  if (!nameOrId) return null;
  const q = nameOrId.toLowerCase().trim();
  return (
    COMPANY_DIRECTORY.find(
      (c) =>
        c.id.toLowerCase() === q ||
        c.name.toLowerCase() === q ||
        c.name.toLowerCase().includes(q) ||
        q.includes(c.id.toLowerCase())
    ) || null
  );
};

module.exports = {
  COMPANY_DIRECTORY,
  findCompany,
};
